import { useState, useEffect } from "react";
import Form from "global/components/form";
import { useTranslation } from "react-i18next";
import { Link, useOutletContext } from "react-router";
import IconComposer from "global/components/utility/IconComposer";
import OutletWithDrawers from "global/components/router/OutletWithDrawers";
import TOCList from "components/backend/authoring/TOCList";
import { formatTreeData } from "components/backend/authoring/TOCList/treeHelpers";
import { textsAPI } from "api";
import { useApiCallback } from "hooks";
import useConfirmation from "hooks/useConfirmation";
import Dialog from "global/components/dialog";
import * as Styled from "./styles";

export default function TextTOCLayout() {
  const { t } = useTranslation();
  const text = useOutletContext();

  const [tocAsDndTree, setTree] = useState(
    formatTreeData(text?.attributes?.toc)
  );
  const [error, setError] = useState(null);

  useEffect(() => {
    if (text?.attributes?.toc) {
      setTree(formatTreeData(text.attributes.toc));
    }
  }, [text?.attributes?.toc]);

  const { confirm, confirmation } = useConfirmation();
  const updateText = useApiCallback(textsAPI.update);

  const onAutoGenerate = async () => {
    setError(null);
    const autoToc = text?.attributes.autoGeneratedTOC;

    const { data, errors } = await updateText(text.id, {
      attributes: { toc: autoToc }
    });
    if (errors) return setError(errors);
    const { toc } = data.attributes;
    setTree(formatTreeData(toc));
  };

  const confirmAutoGenerate = () => {
    const heading = t("modals.auto_generate_toc");
    const message = t("modals.auto_generate_toc_body");
    confirm({
      heading,
      message,
      callback: async closeDialog => {
        await onAutoGenerate();
        closeDialog();
      }
    });
  };

  const closeUrl = `/backend/projects/text/${text.id}/contents`;

  return (
    <section>
      {confirmation && <Dialog.Confirm {...confirmation} />}
      <OutletWithDrawers
        drawerProps={{
          lockScroll: "always",
          wide: true,
          lockScrollClickCloses: false,
          closeUrl
        }}
        context={{
          tree: tocAsDndTree,
          textId: text.id,
          sections: text.attributes?.sectionsMap,
          toc: text.attributes?.toc
        }}
      />
      <Styled.Form
        className="form-secondary"
        doNotWarn
        groupErrors
        model={text}
      >
        <Form.Header
          label={t("texts.toc_header")}
          instructions={t("texts.toc_instructions")}
        />
        <div className="entity-list__button-set-flex full-width">
          <Link
            to={`/backend/projects/text/${text.id}/contents/new`}
            className="entity-list__button button-lozenge-secondary"
          >
            <span className="screen-reader-text">
              {t("texts.add_toc_button_label")}
            </span>
            <IconComposer
              icon="circlePlus32"
              size={18}
              className="button-icon-secondary__icon button-icon-secondary__icon--large"
            />
            <span className="full" aria-hidden="true">
              {t("texts.add_toc_button_label")}
            </span>
          </Link>
          <button
            onClick={confirmAutoGenerate}
            className="entity-list__button button-lozenge-secondary"
          >
            <span className="screen-reader-text">
              {t("texts.auto_toc_button_label")}
            </span>
            <IconComposer
              icon="lightning24"
              size={18}
              className="button-icon-secondary__icon button-icon-secondary__icon--large"
            />
            <span className="full" aria-hidden="true">
              {t("texts.auto_toc_button_label")}
            </span>
          </button>
        </div>
        <TOCList
          toc={text.attributes?.toc}
          tree={tocAsDndTree}
          setTree={setTree}
          textId={text.id}
          error={error}
          setError={setError}
        />
      </Styled.Form>
    </section>
  );
}
