name: "Setup Node.js"
runs:
  using: "composite"
  steps:
    - name: "Enable Corepack"
      shell: bash
      run: corepack enable

    - name: "Install Node"
      uses: actions/setup-node@v6
      with:
        node-version-file: "./client/package.json"
        cache: "yarn"
        cache-dependency-path: ./client/yarn.lock

    - name: "Install dependencies"
      env:
        NODE_ENV: development
      working-directory: "./client"
      shell: bash
      run: yarn install --immutable
