name: "Setup Ruby"
runs:
  using: "composite"
  steps:
    - name: "Install Dependent libraries"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -yqq install imagemagick libpq-dev libvips libvips-dev

    - name: "Install Ruby 2.7.8"
      uses: ruby/setup-ruby@v1
      with:
        bundler: 2.4.19
        bundler-cache: true
        ruby-version: 3.2.3
        working-directory: api
