name: "Setup Ruby"
runs:
  using: "composite"
  steps:
    - name: "Install Dependent libraries"
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -yqq install imagemagick libpq-dev libvips libvips-dev

    - name: "Install Ruby 3.4"
      uses: ruby/setup-ruby@v1
      with:
        bundler: 2.6.2
        bundler-cache: true
        ruby-version: 3.4.9
        working-directory: api
