require "rails_helper"

RSpec.describe Ingestor::Strategy::GoogleDoc::Strategy, :integration do

  shared_examples "output text assertions" do
    describe "the text generated by the ingestion" do

      it "has a nil language value" do
        expect(@text.metadata["language"]).to eq nil
      end

      it "has a title that matches the google doc title" do
        expect(@text.title).to eq "Manifold Test Ingestion"
      end

      it "has a nil rights value" do
        expect(@text.metadata["rights"]).to eq nil
      end

      it "has a nil description value" do
        expect(@text.description).to eq nil
      end

      it "has one text section" do
        expect(@text.text_sections.length).to be 1
      end

      it "has an empty TOC" do
        expect(@text.toc).to eq []
      end

      it "has an empty landmarks property" do
        expect(@text.landmarks).to eq []
      end

      it "has an empty page list" do
        expect(@text.page_list).to eq []
      end

      it "has one stylesheet" do
        expect(@text.stylesheets.length).to eq 2
      end

      it "has one entry in the spine" do
        expect(@text.spine.length).to eq 1
      end

      it "has one ingestion sources" do
        expect(@text.ingestion_sources.length).to eq 17
      end

    end
  end

  after(:all) do
    Ingestor.reset_logger
  end

  context "when pulling source from google drive", :integration do

    before(:all) {
      logger = NullLogger.new
      Ingestor.logger = logger
      Settings.potentially_update_from_environment!
      @creator = FactoryBot.create(:user)
      WebMock.allow_net_connect!
      @google_doc_source = "https://docs.google.com/document/d/1G053ixdCuaNI_2JyrtBm0-ph_0RDAtPtUxDDCmfFeX4/edit?usp=sharing"
      @text = Ingestor.ingest(@google_doc_source, @creator, Ingestor::Strategy::GoogleDoc::Strategy)
      WebMock.disable_net_connect!
    }

    include_examples "output text assertions"

  end
end
