#!/usr/bin/env ruby

require 'optparse'

file = "**/*.scss"

options = {}
OptionParser.new do |opt|
  opt.on('--fix') { options[:fix] = true }
end.parse!

unless ARGV.empty?
  file = ARGV[0].split(" ").select { |arg| arg.end_with?(".", ".scss", ".sass")}.join(" ")
  if file.empty?
    exit(0)
  end
end

command_args = %w(--config=.stylelintrc --color --syntax=scss)
command_args.push "--fix" if options[:fix]
args = command_args.join(" ")

command = "./node_modules/.bin/stylelint #{args} #{file}"

msg = "Linting Sass..."
puts "\e[33m#{msg}\e[0m"
puts "\e[1;30m#{command}\e[0m"

out = `#{command}`
puts out
exit($?.exitstatus)
