Ingestor::Strategy.add(:EPUB, Ingestor::Strategy::EPUB::Strategy)
Ingestor::Strategy.add(:Word, Ingestor::Strategy::Word::Strategy)
Ingestor::Strategy.add(:Gitbook, Ingestor::Strategy::Gitbook::Strategy)
Ingestor::Strategy.add(:GoogleDoc, Ingestor::Strategy::GoogleDoc::Strategy)
Ingestor::Strategy.add(:Html, Ingestor::Strategy::Html::Strategy)
