// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/*";
  };
  "routes/_frontend.jsx": {
    id: "routes/_frontend";
    page: "/";
  };
  "routes/_frontend._index.jsx": {
    id: "routes/_frontend._index";
    page: "/";
  };
  "routes/$.jsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/_frontend": typeof import("./app/routes/_frontend.jsx");
  "routes/_frontend._index": typeof import("./app/routes/_frontend._index.jsx");
  "routes/$": typeof import("./app/routes/$.jsx");
};