// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/project-collections": {
    params: {};
  };
  "/reset-password/:resetToken": {
    params: {
      "resetToken": string;
    };
  };
  "/project-collections/:id": {
    params: {
      "id": string;
    };
  };
  "/journals/issues": {
    params: {};
  };
  "/unsubscribe/:token": {
    params: {
      "token": string;
    };
  };
  "/journals": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/subscriptions": {
    params: {};
  };
  "/journals/:id": {
    params: {
      "id": string;
    };
  };
  "/journals/:id/volumes": {
    params: {
      "id": string;
    };
  };
  "/journals/:id/volumes/:volumeSlug": {
    params: {
      "id": string;
      "volumeSlug": string;
    };
  };
  "/journals/:id/issues": {
    params: {
      "id": string;
    };
  };
  "/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/projects/:id/resource-collection/:resourceCollectionId": {
    params: {
      "id": string;
      "resourceCollectionId": string;
    };
  };
  "/projects/:id/resource-collection/:resourceCollectionId/resource/:resourceId": {
    params: {
      "id": string;
      "resourceCollectionId": string;
      "resourceId": string;
    };
  };
  "/projects/:id/resource-collections": {
    params: {
      "id": string;
    };
  };
  "/projects/:id/resource/:resourceId": {
    params: {
      "id": string;
      "resourceId": string;
    };
  };
  "/projects/:id/resources": {
    params: {
      "id": string;
    };
  };
  "/projects/:id/events": {
    params: {
      "id": string;
    };
  };
  "/projects/:id/search": {
    params: {
      "id": string;
    };
  };
  "/my/starred": {
    params: {};
  };
  "/page/:slug": {
    params: {
      "slug": string;
    };
  };
  "/my/groups": {
    params: {};
  };
  "/my/groups/new": {
    params: {};
  };
  "/data-use": {
    params: {};
  };
  "/docs/api": {
    params: {};
  };
  "/my/notes": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/groups": {
    params: {};
  };
  "/groups/:id": {
    params: {
      "id": string;
    };
  };
  "/groups/:id/annotations": {
    params: {
      "id": string;
    };
  };
  "/groups/:id/annotations/settings": {
    params: {
      "id": string;
    };
  };
  "/groups/:id/settings": {
    params: {
      "id": string;
    };
  };
  "/groups/:id/members": {
    params: {
      "id": string;
    };
  };
  "/groups/:id/members/:membershipId": {
    params: {
      "id": string;
      "membershipId": string;
    };
  };
  "/groups/:id/members/settings": {
    params: {
      "id": string;
    };
  };
  "/groups/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/groups/:id/edit/settings": {
    params: {
      "id": string;
    };
  };
  "/groups/:id/home": {
    params: {
      "id": string;
    };
  };
  "/groups/:id/home/settings": {
    params: {
      "id": string;
    };
  };
  "/search": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/actions/forgot-password": {
    params: {};
  };
  "/actions/update-profile": {
    params: {};
  };
  "/actions/flag-content": {
    params: {};
  };
  "/actions/signup": {
    params: {};
  };
  "/actions/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/project-collections" | "/reset-password/:resetToken" | "/project-collections/:id" | "/journals/issues" | "/unsubscribe/:token" | "/journals" | "/projects" | "/subscriptions" | "/journals/:id" | "/journals/:id/volumes" | "/journals/:id/volumes/:volumeSlug" | "/journals/:id/issues" | "/projects/:id" | "/projects/:id/resource-collection/:resourceCollectionId" | "/projects/:id/resource-collection/:resourceCollectionId/resource/:resourceId" | "/projects/:id/resource-collections" | "/projects/:id/resource/:resourceId" | "/projects/:id/resources" | "/projects/:id/events" | "/projects/:id/search" | "/my/starred" | "/page/:slug" | "/my/groups" | "/my/groups/new" | "/data-use" | "/docs/api" | "/my/notes" | "/contact" | "/privacy" | "/groups" | "/groups/:id" | "/groups/:id/annotations" | "/groups/:id/annotations/settings" | "/groups/:id/settings" | "/groups/:id/members" | "/groups/:id/members/:membershipId" | "/groups/:id/members/settings" | "/groups/:id/edit" | "/groups/:id/edit/settings" | "/groups/:id/home" | "/groups/:id/home/settings" | "/search" | "/signup" | "/login" | "/actions/forgot-password" | "/actions/update-profile" | "/actions/flag-content" | "/actions/signup" | "/actions/login" | "/*";
  };
  "routes/frontend/_frontend/route.jsx": {
    id: "routes/frontend/_frontend";
    page: "/project-collections" | "/reset-password/:resetToken" | "/project-collections/:id" | "/journals/issues" | "/unsubscribe/:token" | "/journals" | "/projects" | "/subscriptions" | "/journals/:id" | "/journals/:id/volumes" | "/journals/:id/volumes/:volumeSlug" | "/journals/:id/issues" | "/projects/:id" | "/projects/:id/resource-collection/:resourceCollectionId" | "/projects/:id/resource-collection/:resourceCollectionId/resource/:resourceId" | "/projects/:id/resource-collections" | "/projects/:id/resource/:resourceId" | "/projects/:id/resources" | "/projects/:id/events" | "/projects/:id/search" | "/my/starred" | "/page/:slug" | "/my/groups" | "/my/groups/new" | "/data-use" | "/docs/api" | "/my/notes" | "/contact" | "/privacy" | "/" | "/groups" | "/groups/:id" | "/groups/:id/annotations" | "/groups/:id/annotations/settings" | "/groups/:id/settings" | "/groups/:id/members" | "/groups/:id/members/:membershipId" | "/groups/:id/members/settings" | "/groups/:id/edit" | "/groups/:id/edit/settings" | "/groups/:id/home" | "/groups/:id/home/settings" | "/search" | "/signup" | "/login";
  };
  "routes/frontend/_frontend.project-collections._index.jsx": {
    id: "routes/frontend/_frontend.project-collections._index";
    page: "/project-collections";
  };
  "routes/frontend/_frontend.reset-password.$resetToken.jsx": {
    id: "routes/frontend/_frontend.reset-password.$resetToken";
    page: "/reset-password/:resetToken";
  };
  "routes/frontend/_frontend.project-collections.$id.jsx": {
    id: "routes/frontend/_frontend.project-collections.$id";
    page: "/project-collections/:id";
  };
  "routes/frontend/_frontend.journals.issues._index.jsx": {
    id: "routes/frontend/_frontend.journals.issues._index";
    page: "/journals/issues";
  };
  "routes/frontend/_frontend.unsubscribe.$token.jsx": {
    id: "routes/frontend/_frontend.unsubscribe.$token";
    page: "/unsubscribe/:token";
  };
  "routes/frontend/_frontend.journals._index.jsx": {
    id: "routes/frontend/_frontend.journals._index";
    page: "/journals";
  };
  "routes/frontend/_frontend.projects._index.jsx": {
    id: "routes/frontend/_frontend.projects._index";
    page: "/projects";
  };
  "routes/frontend/_frontend.subscriptions/route.jsx": {
    id: "routes/frontend/_frontend.subscriptions";
    page: "/subscriptions";
  };
  "routes/frontend/_frontend.journals.$id.jsx": {
    id: "routes/frontend/_frontend.journals.$id";
    page: "/journals/:id" | "/journals/:id/volumes" | "/journals/:id/volumes/:volumeSlug" | "/journals/:id/issues";
  };
  "routes/frontend/_frontend.journals.$id.volumes.jsx": {
    id: "routes/frontend/_frontend.journals.$id.volumes";
    page: "/journals/:id/volumes" | "/journals/:id/volumes/:volumeSlug";
  };
  "routes/frontend/_frontend.journals.$id.volumes.$volumeSlug.jsx": {
    id: "routes/frontend/_frontend.journals.$id.volumes.$volumeSlug";
    page: "/journals/:id/volumes/:volumeSlug";
  };
  "routes/frontend/_frontend.journals.$id.volumes._index.jsx": {
    id: "routes/frontend/_frontend.journals.$id.volumes._index";
    page: "/journals/:id/volumes";
  };
  "routes/frontend/_frontend.journals.$id._index.jsx": {
    id: "routes/frontend/_frontend.journals.$id._index";
    page: "/journals/:id";
  };
  "routes/frontend/_frontend.journals.$id.issues.jsx": {
    id: "routes/frontend/_frontend.journals.$id.issues";
    page: "/journals/:id/issues";
  };
  "routes/frontend/_frontend.projects.$id.jsx": {
    id: "routes/frontend/_frontend.projects.$id";
    page: "/projects/:id" | "/projects/:id/resource-collection/:resourceCollectionId" | "/projects/:id/resource-collection/:resourceCollectionId/resource/:resourceId" | "/projects/:id/resource-collections" | "/projects/:id/resource/:resourceId" | "/projects/:id/resources" | "/projects/:id/events" | "/projects/:id/search";
  };
  "routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId.jsx": {
    id: "routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId";
    page: "/projects/:id/resource-collection/:resourceCollectionId" | "/projects/:id/resource-collection/:resourceCollectionId/resource/:resourceId";
  };
  "routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId.resource.$resourceId.jsx": {
    id: "routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId.resource.$resourceId";
    page: "/projects/:id/resource-collection/:resourceCollectionId/resource/:resourceId";
  };
  "routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId._index.jsx": {
    id: "routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId._index";
    page: "/projects/:id/resource-collection/:resourceCollectionId";
  };
  "routes/frontend/_frontend.projects.$id.resource-collections.jsx": {
    id: "routes/frontend/_frontend.projects.$id.resource-collections";
    page: "/projects/:id/resource-collections";
  };
  "routes/frontend/_frontend.projects.$id.resource.$resourceId.jsx": {
    id: "routes/frontend/_frontend.projects.$id.resource.$resourceId";
    page: "/projects/:id/resource/:resourceId";
  };
  "routes/frontend/_frontend.projects.$id.resources.jsx": {
    id: "routes/frontend/_frontend.projects.$id.resources";
    page: "/projects/:id/resources";
  };
  "routes/frontend/_frontend.projects.$id._index.jsx": {
    id: "routes/frontend/_frontend.projects.$id._index";
    page: "/projects/:id";
  };
  "routes/frontend/_frontend.projects.$id.events.jsx": {
    id: "routes/frontend/_frontend.projects.$id.events";
    page: "/projects/:id/events";
  };
  "routes/frontend/_frontend.projects.$id.search/route.jsx": {
    id: "routes/frontend/_frontend.projects.$id.search";
    page: "/projects/:id/search";
  };
  "routes/frontend/_frontend.my.starred.jsx": {
    id: "routes/frontend/_frontend.my.starred";
    page: "/my/starred";
  };
  "routes/frontend/_frontend.page.$slug.jsx": {
    id: "routes/frontend/_frontend.page.$slug";
    page: "/page/:slug";
  };
  "routes/frontend/_frontend.my.groups.jsx": {
    id: "routes/frontend/_frontend.my.groups";
    page: "/my/groups" | "/my/groups/new";
  };
  "routes/frontend/_frontend.my.groups.new.jsx": {
    id: "routes/frontend/_frontend.my.groups.new";
    page: "/my/groups/new";
  };
  "routes/frontend/_frontend.data-use/route.jsx": {
    id: "routes/frontend/_frontend.data-use";
    page: "/data-use";
  };
  "routes/frontend/_frontend.docs.api.jsx": {
    id: "routes/frontend/_frontend.docs.api";
    page: "/docs/api";
  };
  "routes/frontend/_frontend.my.notes.jsx": {
    id: "routes/frontend/_frontend.my.notes";
    page: "/my/notes";
  };
  "routes/frontend/_frontend.contact.jsx": {
    id: "routes/frontend/_frontend.contact";
    page: "/contact";
  };
  "routes/frontend/_frontend.privacy/route.jsx": {
    id: "routes/frontend/_frontend.privacy";
    page: "/privacy";
  };
  "routes/frontend/_frontend._index.jsx": {
    id: "routes/frontend/_frontend._index";
    page: "/";
  };
  "routes/frontend/_frontend.groups.jsx": {
    id: "routes/frontend/_frontend.groups";
    page: "/groups" | "/groups/:id" | "/groups/:id/annotations" | "/groups/:id/annotations/settings" | "/groups/:id/settings" | "/groups/:id/members" | "/groups/:id/members/:membershipId" | "/groups/:id/members/settings" | "/groups/:id/edit" | "/groups/:id/edit/settings" | "/groups/:id/home" | "/groups/:id/home/settings";
  };
  "routes/frontend/_frontend.groups._index.jsx": {
    id: "routes/frontend/_frontend.groups._index";
    page: "/groups";
  };
  "routes/frontend/_frontend.groups.$id.jsx": {
    id: "routes/frontend/_frontend.groups.$id";
    page: "/groups/:id" | "/groups/:id/annotations" | "/groups/:id/annotations/settings" | "/groups/:id/settings" | "/groups/:id/members" | "/groups/:id/members/:membershipId" | "/groups/:id/members/settings" | "/groups/:id/edit" | "/groups/:id/edit/settings" | "/groups/:id/home" | "/groups/:id/home/settings";
  };
  "routes/frontend/_frontend.groups.$id.annotations/route.jsx": {
    id: "routes/frontend/_frontend.groups.$id.annotations";
    page: "/groups/:id/annotations" | "/groups/:id/annotations/settings";
  };
  "routes/frontend/_frontend.groups.$id.annotations.settings.jsx": {
    id: "routes/frontend/_frontend.groups.$id.annotations.settings";
    page: "/groups/:id/annotations/settings";
  };
  "routes/frontend/_frontend.groups.$id.settings.jsx": {
    id: "routes/frontend/_frontend.groups.$id.settings";
    page: "/groups/:id/settings";
  };
  "routes/frontend/_frontend.groups.$id.members/route.jsx": {
    id: "routes/frontend/_frontend.groups.$id.members";
    page: "/groups/:id/members" | "/groups/:id/members/:membershipId" | "/groups/:id/members/settings";
  };
  "routes/frontend/_frontend.groups.$id.members.$membershipId.jsx": {
    id: "routes/frontend/_frontend.groups.$id.members.$membershipId";
    page: "/groups/:id/members/:membershipId";
  };
  "routes/frontend/_frontend.groups.$id.members.settings.jsx": {
    id: "routes/frontend/_frontend.groups.$id.members.settings";
    page: "/groups/:id/members/settings";
  };
  "routes/frontend/_frontend.groups.$id._index.jsx": {
    id: "routes/frontend/_frontend.groups.$id._index";
    page: "/groups/:id";
  };
  "routes/frontend/_frontend.groups.$id.edit/route.jsx": {
    id: "routes/frontend/_frontend.groups.$id.edit";
    page: "/groups/:id/edit" | "/groups/:id/edit/settings";
  };
  "routes/frontend/_frontend.groups.$id.edit.settings.jsx": {
    id: "routes/frontend/_frontend.groups.$id.edit.settings";
    page: "/groups/:id/edit/settings";
  };
  "routes/frontend/_frontend.groups.$id.home.jsx": {
    id: "routes/frontend/_frontend.groups.$id.home";
    page: "/groups/:id/home" | "/groups/:id/home/settings";
  };
  "routes/frontend/_frontend.groups.$id.home.settings.jsx": {
    id: "routes/frontend/_frontend.groups.$id.home.settings";
    page: "/groups/:id/home/settings";
  };
  "routes/frontend/_frontend.search/route.jsx": {
    id: "routes/frontend/_frontend.search";
    page: "/search";
  };
  "routes/frontend/_frontend.signup.jsx": {
    id: "routes/frontend/_frontend.signup";
    page: "/signup";
  };
  "routes/frontend/_frontend.login.jsx": {
    id: "routes/frontend/_frontend.login";
    page: "/login";
  };
  "routes/global/_global.actions.forgot-password.jsx": {
    id: "routes/global/_global.actions.forgot-password";
    page: "/actions/forgot-password";
  };
  "routes/global/_global.actions.update-profile.jsx": {
    id: "routes/global/_global.actions.update-profile";
    page: "/actions/update-profile";
  };
  "routes/global/_global.actions.flag-content.jsx": {
    id: "routes/global/_global.actions.flag-content";
    page: "/actions/flag-content";
  };
  "routes/global/_global.actions.signup.jsx": {
    id: "routes/global/_global.actions.signup";
    page: "/actions/signup";
  };
  "routes/global/_global.actions.login.jsx": {
    id: "routes/global/_global.actions.login";
    page: "/actions/login";
  };
  "routes/$.jsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/frontend/_frontend": typeof import("./app/routes/frontend/_frontend/route.jsx");
  "routes/frontend/_frontend.project-collections._index": typeof import("./app/routes/frontend/_frontend.project-collections._index.jsx");
  "routes/frontend/_frontend.reset-password.$resetToken": typeof import("./app/routes/frontend/_frontend.reset-password.$resetToken.jsx");
  "routes/frontend/_frontend.project-collections.$id": typeof import("./app/routes/frontend/_frontend.project-collections.$id.jsx");
  "routes/frontend/_frontend.journals.issues._index": typeof import("./app/routes/frontend/_frontend.journals.issues._index.jsx");
  "routes/frontend/_frontend.unsubscribe.$token": typeof import("./app/routes/frontend/_frontend.unsubscribe.$token.jsx");
  "routes/frontend/_frontend.journals._index": typeof import("./app/routes/frontend/_frontend.journals._index.jsx");
  "routes/frontend/_frontend.projects._index": typeof import("./app/routes/frontend/_frontend.projects._index.jsx");
  "routes/frontend/_frontend.subscriptions": typeof import("./app/routes/frontend/_frontend.subscriptions/route.jsx");
  "routes/frontend/_frontend.journals.$id": typeof import("./app/routes/frontend/_frontend.journals.$id.jsx");
  "routes/frontend/_frontend.journals.$id.volumes": typeof import("./app/routes/frontend/_frontend.journals.$id.volumes.jsx");
  "routes/frontend/_frontend.journals.$id.volumes.$volumeSlug": typeof import("./app/routes/frontend/_frontend.journals.$id.volumes.$volumeSlug.jsx");
  "routes/frontend/_frontend.journals.$id.volumes._index": typeof import("./app/routes/frontend/_frontend.journals.$id.volumes._index.jsx");
  "routes/frontend/_frontend.journals.$id._index": typeof import("./app/routes/frontend/_frontend.journals.$id._index.jsx");
  "routes/frontend/_frontend.journals.$id.issues": typeof import("./app/routes/frontend/_frontend.journals.$id.issues.jsx");
  "routes/frontend/_frontend.projects.$id": typeof import("./app/routes/frontend/_frontend.projects.$id.jsx");
  "routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId": typeof import("./app/routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId.jsx");
  "routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId.resource.$resourceId": typeof import("./app/routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId.resource.$resourceId.jsx");
  "routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId._index": typeof import("./app/routes/frontend/_frontend.projects.$id.resource-collection.$resourceCollectionId._index.jsx");
  "routes/frontend/_frontend.projects.$id.resource-collections": typeof import("./app/routes/frontend/_frontend.projects.$id.resource-collections.jsx");
  "routes/frontend/_frontend.projects.$id.resource.$resourceId": typeof import("./app/routes/frontend/_frontend.projects.$id.resource.$resourceId.jsx");
  "routes/frontend/_frontend.projects.$id.resources": typeof import("./app/routes/frontend/_frontend.projects.$id.resources.jsx");
  "routes/frontend/_frontend.projects.$id._index": typeof import("./app/routes/frontend/_frontend.projects.$id._index.jsx");
  "routes/frontend/_frontend.projects.$id.events": typeof import("./app/routes/frontend/_frontend.projects.$id.events.jsx");
  "routes/frontend/_frontend.projects.$id.search": typeof import("./app/routes/frontend/_frontend.projects.$id.search/route.jsx");
  "routes/frontend/_frontend.my.starred": typeof import("./app/routes/frontend/_frontend.my.starred.jsx");
  "routes/frontend/_frontend.page.$slug": typeof import("./app/routes/frontend/_frontend.page.$slug.jsx");
  "routes/frontend/_frontend.my.groups": typeof import("./app/routes/frontend/_frontend.my.groups.jsx");
  "routes/frontend/_frontend.my.groups.new": typeof import("./app/routes/frontend/_frontend.my.groups.new.jsx");
  "routes/frontend/_frontend.data-use": typeof import("./app/routes/frontend/_frontend.data-use/route.jsx");
  "routes/frontend/_frontend.docs.api": typeof import("./app/routes/frontend/_frontend.docs.api.jsx");
  "routes/frontend/_frontend.my.notes": typeof import("./app/routes/frontend/_frontend.my.notes.jsx");
  "routes/frontend/_frontend.contact": typeof import("./app/routes/frontend/_frontend.contact.jsx");
  "routes/frontend/_frontend.privacy": typeof import("./app/routes/frontend/_frontend.privacy/route.jsx");
  "routes/frontend/_frontend._index": typeof import("./app/routes/frontend/_frontend._index.jsx");
  "routes/frontend/_frontend.groups": typeof import("./app/routes/frontend/_frontend.groups.jsx");
  "routes/frontend/_frontend.groups._index": typeof import("./app/routes/frontend/_frontend.groups._index.jsx");
  "routes/frontend/_frontend.groups.$id": typeof import("./app/routes/frontend/_frontend.groups.$id.jsx");
  "routes/frontend/_frontend.groups.$id.annotations": typeof import("./app/routes/frontend/_frontend.groups.$id.annotations/route.jsx");
  "routes/frontend/_frontend.groups.$id.annotations.settings": typeof import("./app/routes/frontend/_frontend.groups.$id.annotations.settings.jsx");
  "routes/frontend/_frontend.groups.$id.settings": typeof import("./app/routes/frontend/_frontend.groups.$id.settings.jsx");
  "routes/frontend/_frontend.groups.$id.members": typeof import("./app/routes/frontend/_frontend.groups.$id.members/route.jsx");
  "routes/frontend/_frontend.groups.$id.members.$membershipId": typeof import("./app/routes/frontend/_frontend.groups.$id.members.$membershipId.jsx");
  "routes/frontend/_frontend.groups.$id.members.settings": typeof import("./app/routes/frontend/_frontend.groups.$id.members.settings.jsx");
  "routes/frontend/_frontend.groups.$id._index": typeof import("./app/routes/frontend/_frontend.groups.$id._index.jsx");
  "routes/frontend/_frontend.groups.$id.edit": typeof import("./app/routes/frontend/_frontend.groups.$id.edit/route.jsx");
  "routes/frontend/_frontend.groups.$id.edit.settings": typeof import("./app/routes/frontend/_frontend.groups.$id.edit.settings.jsx");
  "routes/frontend/_frontend.groups.$id.home": typeof import("./app/routes/frontend/_frontend.groups.$id.home.jsx");
  "routes/frontend/_frontend.groups.$id.home.settings": typeof import("./app/routes/frontend/_frontend.groups.$id.home.settings.jsx");
  "routes/frontend/_frontend.search": typeof import("./app/routes/frontend/_frontend.search/route.jsx");
  "routes/frontend/_frontend.signup": typeof import("./app/routes/frontend/_frontend.signup.jsx");
  "routes/frontend/_frontend.login": typeof import("./app/routes/frontend/_frontend.login.jsx");
  "routes/global/_global.actions.forgot-password": typeof import("./app/routes/global/_global.actions.forgot-password.jsx");
  "routes/global/_global.actions.update-profile": typeof import("./app/routes/global/_global.actions.update-profile.jsx");
  "routes/global/_global.actions.flag-content": typeof import("./app/routes/global/_global.actions.flag-content.jsx");
  "routes/global/_global.actions.signup": typeof import("./app/routes/global/_global.actions.signup.jsx");
  "routes/global/_global.actions.login": typeof import("./app/routes/global/_global.actions.login.jsx");
  "routes/$": typeof import("./app/routes/$.jsx");
};