// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/project-collections": {
    params: {};
  };
  "/journals": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/issues": {
    params: {};
  };
  "/actions/forgot-password": {
    params: {};
  };
  "/actions/update-profile": {
    params: {};
  };
  "/actions/signup": {
    params: {};
  };
  "/actions/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/project-collections" | "/journals" | "/projects" | "/issues" | "/*";
  };
  "routes/frontend/_frontend.jsx": {
    id: "routes/frontend/_frontend";
    page: "/project-collections" | "/journals" | "/projects" | "/issues" | "/";
  };
  "routes/frontend/_frontend.project-collections._index.jsx": {
    id: "routes/frontend/_frontend.project-collections._index";
    page: "/project-collections";
  };
  "routes/frontend/_frontend.journals._index.jsx": {
    id: "routes/frontend/_frontend.journals._index";
    page: "/journals";
  };
  "routes/frontend/_frontend.projects._index.jsx": {
    id: "routes/frontend/_frontend.projects._index";
    page: "/projects";
  };
  "routes/frontend/_frontend.issues._index.jsx": {
    id: "routes/frontend/_frontend.issues._index";
    page: "/issues";
  };
  "routes/frontend/_frontend._index.jsx": {
    id: "routes/frontend/_frontend._index";
    page: "/";
  };
  "routes/global/_global.actions.forgot-password.jsx": {
    id: "routes/global/_global.actions.forgot-password";
    page: "/actions/forgot-password";
  };
  "routes/global/_global.actions.update-profile.jsx": {
    id: "routes/global/_global.actions.update-profile";
    page: "/actions/update-profile";
  };
  "routes/global/_global.actions.signup.jsx": {
    id: "routes/global/_global.actions.signup";
    page: "/actions/signup";
  };
  "routes/global/_global.actions.login.jsx": {
    id: "routes/global/_global.actions.login";
    page: "/actions/login";
  };
  "routes/$.jsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/frontend/_frontend": typeof import("./app/routes/frontend/_frontend.jsx");
  "routes/frontend/_frontend.project-collections._index": typeof import("./app/routes/frontend/_frontend.project-collections._index.jsx");
  "routes/frontend/_frontend.journals._index": typeof import("./app/routes/frontend/_frontend.journals._index.jsx");
  "routes/frontend/_frontend.projects._index": typeof import("./app/routes/frontend/_frontend.projects._index.jsx");
  "routes/frontend/_frontend.issues._index": typeof import("./app/routes/frontend/_frontend.issues._index.jsx");
  "routes/frontend/_frontend._index": typeof import("./app/routes/frontend/_frontend._index.jsx");
  "routes/global/_global.actions.forgot-password": typeof import("./app/routes/global/_global.actions.forgot-password.jsx");
  "routes/global/_global.actions.update-profile": typeof import("./app/routes/global/_global.actions.update-profile.jsx");
  "routes/global/_global.actions.signup": typeof import("./app/routes/global/_global.actions.signup.jsx");
  "routes/global/_global.actions.login": typeof import("./app/routes/global/_global.actions.login.jsx");
  "routes/$": typeof import("./app/routes/$.jsx");
};