<%

  def boxen?; ENV['BOXEN_HOME']; end

  url  = ENV["BOXEN_POSTGRESQL_URL"]
  port = ENV["BOXEN_POSTGRESQL_PORT"]

  if boxen?
    db = 'manifold-api_development'
  else
    user = ENV["RAILS_DB_USER"]
    pass = ENV["RAILS_DB_PASS"]
    db   = ENV["RAILS_DB_NAME"]
  end

%>

common: &common
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 50
  port: <%= port %>
  user: <%= user %>
  database: <%= db %>
  password: <%= pass %>

production:
  <<: *common

demo:
  <<: *common

staging:
  <<: *common

development:
  <<: *common

test:
  <<: *common
  database: manifold-api_test

