#!/bin/bash
set -e
cd "$(dirname "$0")/.."

if which boxen &>/dev/null; then
  echo "Boxen is still installed. Scripts to rule them all is not compatible with Boxen."
  exit 1;
fi

./script/update
cd api &>/dev/null
bin/rails console
