#!/bin/bash
set -e
cd "$(dirname "$0")/.."

if which boxen &>/dev/null; then
  echo "Boxen is still installed. Scripts to rule them all is not compatible with Boxen."
  exit 1;
fi

# ensure everything in the app is up to date.
update="$(dirname "$0")/update"
$update

test -z "$RACK_ENV" &&
  RACK_ENV='development'

foreman start
