#!/bin/bash
set -e
cd "$(dirname "$0")/.."

if which boxen &>/dev/null; then
  echo "Boxen is still installed. Scripts to rule them all is not compatible with Boxen."
  exit 1;
fi

bootstrap="$(dirname "$0")/bootstrap"
$bootstrap

echo "==> Updating db…"
# run all database migrations to ensure everything is up to date.
cd api &> /dev/null
bin/rake db:migrate
cd .. &> /dev/null
