#!/usr/bin/env bash
set -e

install-self-signed-cert
echo "Starting Nginx..."

# Ensure the Docker entrypoint scripts get executed. This includes
# calling `envsubst` on the nginx conf template
bash /docker-entrypoint.sh nginx -g 'daemon off;'
