#!/bin/bash
# Installs Node and NPM.
set -e

echo "==> Checking for Brewfile"

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle --no-upgrade
  }
fi
