common: &1
  :attachments:
    :validations:
      :image:
        :allowed_mime:
          - "image/gif"
          - "image/jpeg"
          - "image/jpg"
          - "image/png"
          - "image/svg+xml"
        :allowed_ext:
          - !ruby/regexp '/gif\Z/'
          - !ruby/regexp '/jpe?g\Z/'
          - !ruby/regexp '/png\Z/'
          - !ruby/regexp '/svg\Z/'
      :resource:
        :allowed_mime:
          - "image/gif"
          - "image/jpeg"
          - "image/png"
          - "image/svg+xml"
          - "application/xhtml+xml"
          - "application/x-dtbncx+xml"
          - "application/vnd.ms-opentype"
          - "application/font-woff"
          - "application/smil+xml"
          - "application/pls+xml"
          - "application/xml"
          - "audio/mpeg"
          - "audio/mp4"
          - "text/css"
          - "text/x-c"
          - "text/javascript"
          - "text/html"
          - "text/plain"
          - "application/x-font-ttf"
          - "application/x-font-truetype"
          - "application/x-font-otf"
          - "video/mp4"
          - "video/webm"
        :allowed_ext:
          - !ruby/regexp '/gif\Z/'
          - !ruby/regexp '/jpe?g\Z/'
          - !ruby/regexp '/png\Z/'
          - !ruby/regexp '/svg\Z/'
          - !ruby/regexp '/x?html\Z/'
          - !ruby/regexp '/ttf\Z/'
          - !ruby/regexp '/otf\Z/'
          - !ruby/regexp '/woff\Z/'
          - !ruby/regexp '/mp3\Z/'
          - !ruby/regexp '/pls\Z/'
          - !ruby/regexp '/smil\Z/'
          - !ruby/regexp '/xml\Z/'
          - !ruby/regexp '/mp3\Z/'
          - !ruby/regexp '/mp4\Z/'
          - !ruby/regexp '/css\Z/'
          - !ruby/regexp '/ncx\Z/'
          - !ruby/regexp '/js\Z/'
          - !ruby/regexp '/webm\Z/'

production: *1
development: *1
test: *1
