common: &1
  :citation_styles:
    :mla: "modern-language-association-8th-edition"
    :chicago: "chicago-annotated-bibliography"
    :apa: "apa"
  :google:
    :analytics_oauth_scope: "https://www.googleapis.com/auth/analytics.readonly"
    :auth_uri: "https://accounts.google.com/o/oauth2/auth"
    :token_uri: "https://accounts.google.com/o/oauth2/token"
    :auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    :client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/"
  :html_validator:
    # The order of these transforms matters. They will be applied in the order listed here.
    # So, you'll want a transform that changes an attribute value to be applied before
    # that attribute is turned into a CSS property.
    :attribute_transforms:
      -
        :name: "width"
        :max: 650
        :type: "max_value"
      -
        :name: "color"
        :type: "css_map"
      -
        :name: "bgcolor"
        :to: "background-color"
        :type: "css_map"
      -
        :name: "align"
        :to: "text-align"
        :type: "css_map"
      -
        :name: "border"
        :type: "measured_css_map"
      -
        :name: "width"
        :type: "measured_css_map"
      -
        # SVG V2 image tags are weird.
        :name: "xlink:href"
        :to: "href"
        :tag: "image"
        :type: "attribute_name"
      -
        :name: "controls"
        :to: true
        :type: "attribute_value"
      -
        :name: "*"
        :type: "namespaced"
    :attribute_exclusions:
      - "accept"
      - "accept-charset"
      - "accesskey"
      - "async"
      - "autofocus"
      - "border"
      - "bgcolor"
      - "challenge"
      - "charset"
      - "code"
      - "codebase"
      - "color"
      - "content"
      - "contenteditable"
      - "defer"
      - "draggable"
      - "dropzone"
      - "height"
      - "keytype"
      - "language"
      - "manifest"
      - "required"
      - "sandbox"
      - "shape"
      - "size"
      - "sizes"
      - "tabindex"
      - "width"
      - "align"

  :css_validator:
    :scope: ".manifold-text-section"
    :dark_scope: ".scheme-dark"
    :selector_replace:
      -
        :match: !ruby/regexp '/(?<=\[)epub\|type(?=.*\])/'
        :search: "|"
        :replace: "-"
    :value_maps:
      -
        :match: !ruby/regexp '/font-size/'
        :entries:
          - ["xx-small", ".7rem"]
          - ["x-small", ".7rem"]
          - ["small", ".8rem"]
          - ["medium", "1rem"]
          - ["large", "1.2rem"]
          - ["x-large", "1.3rem"]
          - ["xx-large", "1.3rem"]
    :invertables:
      :properties:
        :include: ['color', 'background-color', 'border-color', 'border-right-color', 'border-left-color', 'border-top-color', 'border-bottom-color']
    :exclusions:
      :selectors:
        # Strip most universal selectors (while allowing the *= operator)
        - !ruby/regexp '/^\*$|\*:|\s\*$|\*\[/'
        - !ruby/regexp '/^html/'
        - !ruby/regexp '/^body/'
        # All the fonts belong to Manifold
        - !ruby/regexp '/@font-face/'
        # CSS at rules are extracted before selectors are validated, so we exclude them as a selector.
        - !ruby/regexp '/^@(.*);$/'
      :properties:
        -
          :exclude: ['position', 'font-family', 'overflow', 'overflow-x', 'overflow-y', 'z-index', 'max-width', 'line-height', 'letter-spacing']
        -
          :condition:
            :match: !ruby/regexp '/\d+pt|\d+px/'
            :type: "value"
          :exclude: ['font-size']
        -
          :condition:
            :match: !ruby/regexp '/^400|normal$/'
            :type: "value"
          :exclude: ['font-weight']
        -
          :condition:
            :match: !ruby/regexp '/^(h1|h2|h3|h4|h5|h6)$/i'
            :type: "selector_tag"
          :exclude: ['font-weight', 'size', 'font-size', 'line-height', 'margin', 'margin-top', 'margin-bottom', 'margin-left', 'margin-right', 'padding', 'padding-top', 'padding-bottom', 'padding-left', 'padding-right', 'color']
        -
          :condition:
            :match: !ruby/regexp '/^(p)$/i'
            :type: "selector_tag"
          :exclude: ['font-weight', 'size', 'font-size', 'line-height']
        -
          :condition:
            :match: !ruby/regexp '/^div$/'
            :type: "selector_tag"
          :exclude: ['width']
        -
          :condition:
            :match: !ruby/regexp '/^[a]$/'
            :type: "selector_tag"
          :exclude: ['color']

  :attachments:
    :validations:
      :csv:
        :allowed_mime:
          - "text/csv"
          - "text/plain"
        :allowed_ext:
          - !ruby/regexp '/csv\Z/i'
      :ingestion:
        :allowed_mime:
          - "text/markdown"
          - "text/plain"
          - "text/html"
          - "text/yaml"
          - "application/markdown"
          - "application/x-latex"
          - "text/x-latex"
          - "application/x-tex"
          - "text/x-tex"
          - "application/zip"
          - "application/x-yaml"
          - "application/epub+zip"
          - "application/xhtml+xml"
          - "application/msword"
          - "application/vnd.ms-word.document.macroEnabled.12"
          - "application/vnd.ms-word.template.macroEnabled.12"
          - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
          - "application/vnd.openxmlformats-officedocument.wordprocessingml.template"
        :allowed_ext:
          - md
          - zip
          - epub
          - htm
          - html
          - docx
          - yaml
          - yml
          - tex
          - latex
      :image:
        :allowed_mime:
          - !ruby/regexp '/image\/.*/'
        :allowed_ext:
          - !ruby/regexp '/gif\Z/i'
          - !ruby/regexp '/jpe?g\Z/i'
          - !ruby/regexp '/png\Z/i'
      :video:
        :allowed_mime:
          - !ruby/regexp '/video\/.*/'
        :allowed_ext:
          - !ruby/regexp '/mp4\Z/i'
          - !ruby/regexp '/webm\Z/i'
          - !ruby/regexp '/flv\Z/i'
          - !ruby/regexp '/mov\Z/i'
          - !ruby/regexp '/avi\Z/i'
      :audio:
        :allowed_mime:
          - !ruby/regexp '/audio\/.*/'
          - !ruby/regexp '/video\/ogg/'
        :allowed_ext:
          - !ruby/regexp '/flac\Z/i'
          - !ruby/regexp '/mp3\Z/i'
          - !ruby/regexp '/wav\Z/i'
          - !ruby/regexp '/ogg\Z/i'
          - !ruby/regexp '/oga\Z/i'
      :spreadsheet:
        :allowed_mime:
          - "application/vnd.ms-excel"
          - "application/msexcel"
          - "application/x-msexcel"
          - "application/x-ms-excel"
          - "application/x-excel"
          - "application/x-dos_ms_excel"
          - "application/xls"
          - "application/x-xls"
          - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
          - "application/vnd.oasis.opendocument.spreadsheet"
          - "application/vnd.oasis.opendocument.spreadsheet-template"
          - "application/zip"
          - "text/csv"
        :allowed_ext:
          - !ruby/regexp '/xls\Z/i'
          - !ruby/regexp '/xlt\Z/i'
          - !ruby/regexp '/xlm\Z/i'
          - !ruby/regexp '/xlsx\Z/i'
          - !ruby/regexp '/xlsm\Z/i'
          - !ruby/regexp '/xltx\Z/i'
          - !ruby/regexp '/xltm\Z/i'
          - !ruby/regexp '/xlsb\Z/i'
          - !ruby/regexp '/xla\Z/i'
          - !ruby/regexp '/xlw\Z/i'
          - !ruby/regexp '/csv\Z/i'
          - !ruby/regexp '/ods\Z/i'
          - !ruby/regexp '/ots\Z/i'
      :text_document:
        :allowed_mime:
          - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
          - "application/vnd.openxmlformats-officedocument.wordprocessingml.template"
          - "application/msword"
          - "application/vnd.ms-word.document.macroEnabled.12"
          - "application/vnd.ms-word.template.macroEnabled.12"
          - "application/rtf"
          - "application/vnd.oasis.opendocument.text"
          - "application/vnd.oasis.opendocument.text-template"
          - !ruby/regexp '/text\/.*/'
        :allowed_ext:
          - !ruby/regexp '/doc\Z/i'
          - !ruby/regexp '/docx\Z/i'
          - !ruby/regexp '/docm\Z/i'
          - !ruby/regexp '/dotx\Z/i'
          - !ruby/regexp '/dotm\Z/i'
          - !ruby/regexp '/docb\Z/i'
          - !ruby/regexp '/odt\Z/i'
          - !ruby/regexp '/ott\Z/i'
          - !ruby/regexp '/txt\Z/i'
          - !ruby/regexp '/rtf\Z/i'
      :presentation:
        :allowed_mime:
          - "application/zip" # https://github.com/ManifoldScholar/manifold/issues/936
          - "application/vnd.ms-powerpoint"
          - "application/vnd.openxmlformats-officedocument.presentationml.presentation"
          - "application/vnd.openxmlformats-officedocument.presentationml.template"
          - "application/vnd.openxmlformats-officedocument.presentationml.slideshow"
          - "application/vnd.oasis.opendocument.presentation"
          - "application/vnd.oasis.opendocument.presentation-template"
        :allowed_ext:
          - !ruby/regexp '/ppt\Z/i'
          - !ruby/regexp '/pptx\Z/i'
          - !ruby/regexp '/pptm\Z/i'
          - !ruby/regexp '/potx\Z/i'
          - !ruby/regexp '/potm\Z/i'
          - !ruby/regexp '/ppam\Z/i'
          - !ruby/regexp '/ppsx\Z/i'
          - !ruby/regexp '/ppsm\Z/i'
          - !ruby/regexp '/sldx\Z/i'
          - !ruby/regexp '/sldm\Z/i'
          - !ruby/regexp '/odp\Z/i'
          - !ruby/regexp '/otp\Z/i'
      :pdf:
        :allowed_mime:
          - "application/pdf"
        :allowed_ext:
          - !ruby/regexp '/pdf\Z/'
      :resource:
        :allowed_mime:
          - "application/xhtml+xml"
          - "application/x-dtbncx+xml"
          - "application/vnd.ms-opentype"
          - "application/font-woff"
          - "application/smil+xml"
          - "application/pls+xml"
          - "application/xml"
          - "application/pdf"
          - "application/vnd.ms-powerpoint"
          - "application/x-font-ttf"
          - "application/x-font-truetype"
          - "application/x-font-otf"
          - "application/x-apple-diskimage"
          - "application/x-bzip"
          - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
          - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
          - "application/vnd.openxmlformats-officedocument.presentationml.presentation"
          - "application/zip"
          - "application/markdown"
          - "application/epub+zip"
          - "application/rtf"
          - "application/vnd.oasis.opendocument.spreadsheet"
          - "application/vnd.oasis.opendocument.text"
          - "application/vnd.oasis.opendocument.presentation"
          - "application/x-latex"
          - "text/x-latex"
          - "application/x-tex"
          - "text/x-tex"
          - "text/csv"
          - "text/plain"
          - !ruby/regexp '/text\/.*/'
          - !ruby/regexp '/audio\/.*/'
          - !ruby/regexp '/video\/.*/'
          - !ruby/regexp '/image\/.*/'
        :allowed_ext:
          # Image
          - !ruby/regexp '/gif\Z/i'
          - !ruby/regexp '/jpe?g\Z/i'
          - !ruby/regexp '/png\Z/i'
          - !ruby/regexp '/svg\Z/i'
          # Video
          - !ruby/regexp '/mp4\Z/i'
          - !ruby/regexp '/webm\Z/i'
          - !ruby/regexp '/flv\Z/i'
          - !ruby/regexp '/mov\Z/i'
          - !ruby/regexp '/avi\Z/i'
          # Audio
          - !ruby/regexp '/flac\Z/i'
          - !ruby/regexp '/mp3\Z/i'
          - !ruby/regexp '/wav\Z/i'
          - !ruby/regexp '/ogg\Z/i'
          - !ruby/regexp '/oga\Z/i'
          # Spreadsheet
          - !ruby/regexp '/xls\Z/i'
          - !ruby/regexp '/xlt\Z/i'
          - !ruby/regexp '/xlm\Z/i'
          - !ruby/regexp '/xlsx\Z/i'
          - !ruby/regexp '/xlsm\Z/i'
          - !ruby/regexp '/xltx\Z/i'
          - !ruby/regexp '/xltm\Z/i'
          - !ruby/regexp '/xlsb\Z/i'
          - !ruby/regexp '/xla\Z/i'
          - !ruby/regexp '/xlw\Z/i'
          - !ruby/regexp '/csv\Z/i'
          - !ruby/regexp '/ods\Z/i'
          - !ruby/regexp '/ots\Z/i'
          # Document
          - !ruby/regexp '/doc\Z/i'
          - !ruby/regexp '/docx\Z/i'
          - !ruby/regexp '/docm\Z/i'
          - !ruby/regexp '/dotx\Z/i'
          - !ruby/regexp '/dotm\Z/i'
          - !ruby/regexp '/docb\Z/i'
          - !ruby/regexp '/odt\Z/i'
          - !ruby/regexp '/ott\Z/i'
          - !ruby/regexp '/txt\Z/i'
          - !ruby/regexp '/rtf\Z/i'
          # Presentation
          - !ruby/regexp '/ppt\Z/i'
          - !ruby/regexp '/pptx\Z/i'
          - !ruby/regexp '/pptm\Z/i'
          - !ruby/regexp '/potx\Z/i'
          - !ruby/regexp '/potm\Z/i'
          - !ruby/regexp '/ppam\Z/i'
          - !ruby/regexp '/ppsx\Z/i'
          - !ruby/regexp '/ppsm\Z/i'
          - !ruby/regexp '/sldx\Z/i'
          - !ruby/regexp '/sldm\Z/i'
          - !ruby/regexp '/odp\Z/i'
          - !ruby/regexp '/otp\Z/i'
          # File
          - !ruby/regexp '/zip\Z/i'
          - !ruby/regexp '/md\Z/i'
          - !ruby/regexp '/epub\Z/i'
          - !ruby/regexp '/pls\Z/i'
          - !ruby/regexp '/ncx\Z/i'
          - !ruby/regexp '/dmg\Z/i'
          - !ruby/regexp '/mid\Z/i'
          - !ruby/regexp '/wma\Z/i'
          - !ruby/regexp '/wmv\Z/i'
          - !ruby/regexp '/tex\Z/i'
          - !ruby/regexp '/latex\Z/i'
          # PDF
          - !ruby/regexp '/pdf\Z/'
          # Misc
          - !ruby/regexp '/tex\Z/i'
          - !ruby/regexp '/latex\Z/i'
          - !ruby/regexp '/js\Z/i'
          - !ruby/regexp '/x?html?\Z/i'
          - !ruby/regexp '/ttf\Z/i'
          - !ruby/regexp '/otf\Z/i'
          - !ruby/regexp '/woff\Z/i'
          - !ruby/regexp '/css\Z/i'
          - !ruby/regexp '/xml\Z/i'
          - !ruby/regexp '/smil\Z/i'
          - !ruby/regexp '/ya?ml\Z/i'
production: *1
development: *1
test: *1
