common: &1
  :attachments:
    :validations:
      :image:
        :allowed_mime:
          - !ruby/regexp '/image\/.*/'
        :allowed_ext:
          - !ruby/regexp '/gif\Z/'
          - !ruby/regexp '/jpe?g\Z/'
          - !ruby/regexp '/png\Z/'
          - !ruby/regexp '/svg\Z/'
      :resource:
        :allowed_mime:
          - "application/xhtml+xml"
          - "application/x-dtbncx+xml"
          - "application/vnd.ms-opentype"
          - "application/font-woff"
          - "application/smil+xml"
          - "application/pls+xml"
          - "application/xml"
          - "application/pdf"
          - "application/vnd.ms-powerpoint"
          - "application/x-font-ttf"
          - "application/x-font-truetype"
          - "application/x-font-otf"
          - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
          - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
          - "application/vnd.openxmlformats-officedocument.presentationml.presentation"
          - "application/zip"
          - !ruby/regexp '/text\/.*/'
          - !ruby/regexp '/audio\/.*/'
          - !ruby/regexp '/video\/.*/'
          - !ruby/regexp '/image\/.*/'
        :allowed_ext:
          - !ruby/regexp '/gif\Z/'
          - !ruby/regexp '/jpe?g\Z/'
          - !ruby/regexp '/png\Z/'
          - !ruby/regexp '/svg\Z/'
          - !ruby/regexp '/x?html\Z/'
          - !ruby/regexp '/ttf\Z/'
          - !ruby/regexp '/otf\Z/'
          - !ruby/regexp '/woff\Z/'
          - !ruby/regexp '/mp3\Z/'
          - !ruby/regexp '/pls\Z/'
          - !ruby/regexp '/smil\Z/'
          - !ruby/regexp '/xml\Z/'
          - !ruby/regexp '/mp3\Z/'
          - !ruby/regexp '/mp4\Z/'
          - !ruby/regexp '/css\Z/'
          - !ruby/regexp '/ncx\Z/'
          - !ruby/regexp '/js\Z/'
          - !ruby/regexp '/webm\Z/'
          - !ruby/regexp '/pdf\Z/'
          - !ruby/regexp '/zip\Z/'
          - !ruby/regexp '/docx\Z/'
          - !ruby/regexp '/xlsx\Z/'
          - !ruby/regexp '/ppt?x\Z/'
          - !ruby/regexp '/md\Z/'

production: *1
development: *1
test: *1
