default: &default
#  bucket: ""
#  endpoint: ""
#  access_key_id: ""
#  secret_access_key: ""
#  region: ""
  force_path_style: false

development:
  <<: *default
  endpoint: http://seaweedfs:8333
  access_key_id: manifold
  secret_access_key: manifold-dev-secret
  region: "us-east-1"
  force_path_style: true
  public: true

test:
  <<: *default
  access_key_id: manifold
  secret_access_key: manifold-dev-secret
  region: "us-east-1"

production:
  <<: *default
