default: &default
  database: cache
  store_options:
    max_age: <%= 1.week.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= ENV.fetch("RAILS_CACHE_NAMESPACE", "manifold") %>

production:
  <<: *default

demo:
  <<: *default

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
