replicaCount: 1

imagePullSecrets:
  - name: github

volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: princeton-manifold-production-shared-pvc

resources:
  limits:
    memory: "4Gi"
    cpu: "600m"
  requests:
    memory: "2Gi"
    cpu: "300m"

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

ingress:
  enabled: true
  hosts:
    - host: princeton-manifold-production.softserv.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    cert-manager.io/cluster-issuer: "letsencrypt-production-dns"
  tls:
    - hosts:
        - princeton-manifold-production.softserv.cloud
      secretName: production-princeton-manifold-tls

redis:
  enabled: true
  architecture: standalone
  auth:
    password: $REDIS_PASSWORD # FIXME need to set

env:
  rails_secret_key: $RAILS_SECRET_KEY

externalPostgresql:
  host: acid-postgres-cluster-delta.postgres.svc.cluster.local
  username: princeton_manifold
  password: $DB_PASSWORD
  database: princeton_manifold_production

nginx:
  enabled: true
  service:
    type: ClusterIP
  image:
    repository: ghcr.io/scientist-softserv/princeton-manifold/nginx
    tag: $TAG
