replicaCount: 1

imagePullSecrets:
  - name: github

resources:
  limits:
    memory: "4Gi"
    cpu: "600m"
  requests:
    memory: "2Gi"
    cpu: "300m"

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

ingress:
  enabled: true
  hosts:
    - host: princeton-manifold-production.softserv.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    cert-manager.io/cluster-issuer: "letsencrypt-production-dns"
  tls:
    - hosts:
        - princeton-manifold-production.softserv.cloud
      secretName: production-princeton-manifold-tls

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: "OnRootMismatch"

redis:
  enabled: true
  architecture: standalone
  auth:
    password: $REDIS_PASSWORD # FIXME need to set

nginx:
  enabled: true
  service:
    type: ClusterIP
  image:
    repository: ghcr.io/scientist-softserv/princeton-manifold/nginx
    tag: $TAG
