apiVersion: v1
kind: Service
metadata:
  name: {{ include "princeton-manifold.fullname" . }}
  labels:
    {{- include "princeton-manifold.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "princeton-manifold.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
