name: "Setup Elasticsearch"
runs:
  using: "composite"
  steps:
    - name: Configure sysctl limits
      shell: bash
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
        sudo sysctl -w fs.inotify.max_user_watches=524288

    - name: Runs Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        security-enabled: false
        stack-version: 7.12.0
