AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
      - 'vendor/**/*'
      - 'db/**/*'
      - 'bin/**/*'
      - 'spec/**/*'
      - 'api/vendor/**/*'
      - 'api/db/**/*'
      - 'api/bin/**/*'
      - 'api/spec/**/*'
      - 'api/lib/patches/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/CollectionMethods:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Rails:
  Enabled: true

Naming/HeredocDelimiterNaming:
  Enabled: false

Lint/UnneededCopDisableDirective:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Rails/Blank:
  Enabled: false

Rails/Present:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - 'ok'
    - 'id'
    - 'io'
    - 'e'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit
