AllCops:
  DisplayCopNames: true
  Exclude:
      - 'vendor/**/*'
      - 'db/**/*'
      - 'bin/**/*'
      - 'spec/**/*'
      - 'api/vendor/**/*'
      - 'api/db/**/*'
      - 'api/bin/**/*'
      - 'api/spec/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 15

Style/DotPosition:
  EnforcedStyle: leading

Rails:
  Enabled: true

Lint/UnneededDisable:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false
