AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
      - 'vendor/**/*'
      - 'db/**/*'
      - 'bin/**/*'
      - 'spec/**/*'
      - 'lib/patches/**/*'
      - 'lib/templates/**/*'
      - 'api/vendor/**/*'
      - 'api/db/**/*'
      - 'api/bin/**/*'
      - 'api/spec/**/*'
      - 'api/lib/patches/**/*'
      - 'api/lib/templates/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/CollectionMethods:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/IndentHeredoc:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/PredicateName:
  NamePrefixBlacklist: ["is_"]

Lint/AmbiguousBlockAssociation:
  Enabled: false

# This complains about perfectly valid delegation syntax
Lint/AmbiguousOperator:
  Enabled: false

Lint/UnneededCopDisableDirective:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/Lambda:
  Enabled: false

# This is acceptable Ruby syntax for callables
Style/LambdaCall:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantReturn:
  Exclude:
    # Interactions often benefit from being able to explicitly return
    # to distinguish typos
    - app/services/**/*.rb
    - api/app/services/**/*.rb

Style/SymbolArray:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    # classy_enum generates them this way for clarity,
    # since they need to be loaded in one file to work.
    - app/enums/**/*.rb
    - api/app/enums/**/*.rb

Lint/ScriptPermission:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - 'as'
    - 'ok'
    - 'id'
    - 'io'
    - 'e'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'zhong.rb'

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit
