AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Exclude:
      - 'vendor/**/*'
      - 'spec/**/*'
      - 'db/**/*'
      - 'bin/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 15
