AllCops:
  DisplayCopNames: true
  Exclude:
      - 'vendor/**/*'
      - 'db/**/*'
      - 'bin/**/*'
      - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 15

Style/DotPosition:
  EnforcedStyle: leading

Rails:
  Enabled: true
