source "https://rubygems.org"

gem "rails", github: "rails/rails"
gem "sprockets-rails", github: "rails/sprockets-rails"
gem "sprockets", github: "rails/sprockets"
gem "sass-rails", github: "rails/sass-rails"
gem "arel", github: "rails/arel"
gem "rack", github: "rack/rack"

# Use sqlite3 as the database for Active Record
gem "pg"
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Puma as the app server
gem "puma", "~> 2.14"

# Use Capistrano for deployment
gem "capistrano-rails", group: :development
gem "capistrano-rbenv", group: :development

# Use ActiveModelSerializers to serialize JSON responses
gem "active_model_serializers", "~> 0.10.0.rc2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin
# AJAX possible
gem "rack-cors"

gem "rubyzip", ">= 1.0.0"
gem "nokogiri"
gem "paperclip", "~> 4.3"
gem "memoist", "~> 0.12.0"
gem "naught", "~> 1.0.0"
gem "filesize", "~> 0.1.1"
gem "faker", github: "stympy/faker"
gem "httparty", "~> 0.13.7"

group :development, :test do
  gem "rspec-rails", "~> 3.0"
  gem "factory_girl"
end

group :development do
  # Spring speeds up development by keeping your application running in the background.
  # Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-commands-rspec"
  gem "rubocop"
end
