source "https://rubygems.org"

gem "active_model_serializers", "~> 0.10.2"
# Locked until this is resolved:
# https://github.com/swanandp/acts_as_list/issues/253
gem "acts_as_list", "~>0.8.2"
gem "authority", "~>3.2.0"
gem "bcrypt", "~> 3.1.11"
gem "clockwork", "2.0.0"
gem "colorize"
gem "css_parser"
gem "dotenv-rails"
gem "faker", github: "stympy/faker"
gem "filesize", "~> 0.1.1"
gem "foreman", "0.82.0"
gem "friendly_id"
gem "google-api-client"
gem "google_drive"
gem "hashie"
gem "has_scope"
gem "httparty", "~> 0.14.0"
gem "jwt", "~> 1.5.6"
gem "kaminari", "0.17.0"
gem "memoist", "~> 0.15.0"
gem "metadown"
gem "money"
gem "naught", "~> 1.1.0"
gem "nokogiri"
gem "paperclip", "~> 5.1.0"
gem "pg"
gem "puma", "~> 3.6.0"
gem "rack-cors"
gem "rails", "~> 5.0.1"
gem "rainbow"
gem "redcarpet"
gem "rubyzip", ">= 1.2.0"
gem "searchkick"
gem "sidekiq", "4.2.3"
gem "signet"
gem "twitter", "5.16.0"
gem "uber"
gem "validate_url"

group :development, :test do
  gem "factory_girl_rails", "~> 4.7"
  gem "rspec-core", "~> 3.5.0"
  gem "rspec-expectations", "~> 3.5.0"
  gem "rspec-mocks", "~> 3.5.0"
  gem "rspec-rails", "~> 3.5.0"
  gem "rspec-support", "~> 3.5.0"
end

group :development do
  gem "rubocop"
  gem "spring"
  gem "spring-commands-rspec"
  gem "webmock"
end

group :test do
  gem "database_cleaner"
end
