source "https://rubygems.org"

gem "aasm", "~> 4.0"
gem "active_interaction", "~> 3.0"
gem "active_model_serializers", "~> 0.10"
gem "activejob-retry", "~> 0.4"
gem "activejob-traffic_control", "~>0.1.0"
gem "activerecord-import", "~> 0.22.0"
gem "acts-as-taggable-on", "~> 5.0"
# Locked until this is resolved:
# https://github.com/swanandp/acts_as_list/issues/253
gem "acts_as_list", "~>0.8.2"
# Project is now unmaintained. Fixing to 3.3 for now.
gem "authority", "~>3.3.0"
gem "bcrypt", "~> 3.0"
gem "chroma", "~> 0.2"
gem "citeproc-ruby", "~> 1.1.0"
gem "clockwork", "~> 2.0.0"
gem "closure_tree", "~> 6.0"
gem "colorize", "~> 0.8.0"
gem "csl-styles", "~> 1.0"
gem "css_parser", "~> 1.0"
gem "data_uri", "~> 0.1.0"
gem "dotenv-rails", "~> 2.0"
gem "faker", "~> 1.0"
gem "filesize", "~> 0.1.0"
gem "foreman", "~> 0.84.0"
gem "friendly_id", "~> 5.0"
gem "google-api-client", "~> 0.13.0"
gem "google_drive", "~> 2.0"
gem "has_scope", "~> 0.7.0"
gem "hashie", "~> 3.0"
gem "httparty", "~> 0.15.0"
gem "kaminari", "~> 1.0"
gem "memoist", "~> 0.16.0"
gem "metadown", "~> 1.0"
gem "money", "~> 6.0"
gem "namae", "~>1.0"
gem "naught", "~> 1.0"
gem "nokogiri", "~> 1.0"
gem "paleta", "~> 0.3.0"
gem "paper_trail", "~> 8.0"
gem "paper_trail-globalid", "~> 0.2"
gem "paperclip", "~> 5.0"
# Rails does not yet support PG 1.0; it's in master for rails, but not released as of
# Jan 25, 2018. See https://github.com/rails/rails/issues/31669
gem "pg", "~> 0.21.0"
gem "premailer-rails", "~> 1.0"
gem "pry-rails", "~> 0.3.0"
gem "puma", "~> 3.0"
# We can't upgrade to rails 5.1 until this is addressed:
# https://github.com/mbleigh/acts-as-taggable-on/issues/836
gem "elasticsearch", "~> 5.0"
gem "jwt", "~> 1.5.6"
gem "oauth2", "~> 1.3.1"
gem "omniauth", "~> 1.6.1"
gem "omniauth-facebook", "~> 4.0.0"
gem "omniauth-google-oauth2", "~> 0.4.1"
gem "omniauth-twitter", "~> 1.4.0"
gem "rack-cors", "~> 1.0"
gem "rails", "~> 5.0.0"
# This can go to 3.0 when we're ready to upgrade Rubocop to 0.52
gem "rainbow", "~> 2.0"
gem "redcarpet", "~> 3.0"
# As of Jan 28, 2018, ActionCable requires redis ~> 3.0
# See https://github.com/rails/rails/issues/30527
gem "redis", "~> 3.0"
gem "redis-namespace", "~> 1.0"
gem "redis-objects", "~> 1.3.0"
gem "redis-rails", "~> 5.0"
gem "rolify", "~> 5.0"
gem "rubyzip", "~> 1.0"
gem "scenic", "~> 1.4"
gem "searchkick", "~> 2.0"
gem "sidekiq", "~> 5.0"
gem "signet", "~> 0.8.0"
gem "statesman", "~> 3.4.1"
gem "twitter", "~> 6.0"
gem "uber", "~> 0.1.0", require: %w(uber/inheritable_attr)
gem "validate_url", "~> 1.0"
gem "validates_email_format_of", "~> 1.0"

group :development, :test do
  gem "factory_bot_rails", "~> 4.0"
  gem "rspec-core", "~> 3.0"
  gem "rspec-expectations", "~> 3.0"
  gem "rspec-json_expectations", "~> 2.0"
  gem "rspec-mocks", "~> 3.0"
  gem "rspec-rails", "~> 3.0"
  gem "rspec-support", "~> 3.0"
  gem "timecop", "~> 0.9"
end

group :development do
  gem "rubocop", "~> 0.54.0"
  gem "spring", "~> 2.0"
  gem "spring-commands-rspec", "~> 1.0"
  gem "webmock", "~> 3.0"
end

group :test do
  gem "database_cleaner", "~> 1.0"
end
