name: Continuous Integration

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
env:
  BROWSERSLIST_IGNORE_OLD_DATA: beQuiet
  DISABLE_SPRING: yes
  PATH: /usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/sbin
  RAILS_ENV: test
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/manifold_test"
  CACHE_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/manifold_cache_test"

jobs:
  client-lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - run: corepack enable
      - uses: ./.github/actions/setup-node

      - name: "Lint client"
        working-directory: "./client"
        run: yarn lint

      - name: "Check for unused dependencies"
        working-directory: "./client"
        run: yarn depcheck

  client-build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - run: corepack enable
      - uses: ./.github/actions/setup-node

      - name: "Build client"
        working-directory: "./client"
        run: yarn build

  api-lint:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-ruby

      - name: "Run Rubocop"
        working-directory: "./api"
        run: bin/rubocop

  api-tests:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.12-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-ruby

      - run: corepack enable
      - uses: ./.github/actions/setup-node

      - name: "Install Pandoc"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.2/pandoc-2.2-1-amd64.deb
          sudo dpkg -i pandoc-2.2-1-amd64.deb

      - name: "Setup test database"
        working-directory: "./api"
        run: bin/rails db:test:prepare

      - name: "Run API specs"
        working-directory: "./api"
        run: bin/rspec spec --tag="~integration" --tag="~slow"
