name: Holla Back Bot

# To trigger this workflow, post a comment like @bot bug
on:
  issue_comment:
    types: [created]

jobs:
  issue-auto-reply:
    runs-on: ubuntu-latest
    steps:
      - uses: "ManifoldScholar/issue-autorespond-action@master"
        id: "issue-autorespond"
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          config: |
            [
              {
                "cmd": "bug",
                "labels": ["Type: Bug", "Status: Planned"],
                "message": "master:.github/workflows/hollas/bug_accepted.md",
                "close": false
              },
              {
                "cmd": "accept",
                "labels": ["Type: Enhancement", "Status: Accepted"],
                "message": "master:.github/workflows/hollas/in_scope_accepted.md",
                "close": false
              },
              {
                "cmd": "funding",
                "labels": ["Type: Enhancement", "Status: Funding Needed"],
                "message": "master:.github/workflows/hollas/in_scope_needs_funding.md",
                "close": true
              },
              {
                "cmd": "planned",
                "labels": ["Type: Enhancement", "Status: Planned"],
                "message": "master:.github/workflows/hollas/in_scope_planned.md",
                "close": false
              },
              {
                "cmd": "reject",
                "labels": ["Status: Out of Scope"],
                "message": "master:.github/workflows/hollas/out_of_scope.md",
                "close": true
              }
            ]



