name: Production Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Update Release Branch
    runs-on: ubuntu-latest
    steps:
      - name: "checkout release-candidate"
        uses: actions/checkout@v6
        with:
          ref: release

      - name: "Push release changes"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git fetch
          git reset --hard origin/main
          git push --force origin release